apiVersion: v1
kind: Service
metadata: 
  name: web-service-prod
  labels: 
    app: web
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector: 
    app: web
    version: "web-#{Release.Artifacts.image.BuildId}#"
  type: LoadBalancer
