apiVersion: v1
kind: Service
metadata: 
  name: web-service-prod
  labels: 
    name: web
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector: 
    app: web
    version: "web-#{Release.Artifacts.image.BuildId}#"
  type: NodePort
