trigger:
    - none

pool:
    vmImage: Ubuntu-16.04

variables:
    imageName: dpolania/blue-green

steps:
  - task: Docker@2
    displayName: Build and push image
    inputs:
      containerRegistry: DockerHub
      repository: $(imageName)
      command: buildAndPush
      Dockerfile: src/Dockerfile
      tags: |
        $(Build.BuildId)