apiVersion: apps/v1
kind: Deployment
metadata:
  name: "#{app}#-#{version}#"
  labels:
    app: "#{app}#"
    type: "#{deploy}#"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "#{app}#"
      version: "#{app}#-#{version}#"
  template:
    metadata:
      labels:
        app: "#{app}#"
        version: "#{app}#-#{version}#"
    spec:
      containers: 
        - name: "#{app}#"
          image: "#{containerRegistry}#/#{imageName}#"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80