apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-#{Release.Artifacts.image.BuildId}#
  labels:
    app: web
    type: "#{deploy}#"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      version: "web-#{Release.Artifacts.image.BuildId}#"
  template:
    metadata:
      labels:
        app: web
        version: "web-#{Release.Artifacts.image.BuildId}#"
    spec:
      containers: 
        - name: web
          image: dpolania/blue-green
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80