apiVersion: v1
kind: Service
metadata: 
  name: web-service-temp
  labels: 
    app: web
    type: "#{deploy}#"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector: 
    app: web
    type: "#{deploy}#"
  type: LoadBalancer

