apiVersion: v1
kind: Service
metadata: 
  name: web-service-#{env}#
  labels: 
    name: web
    version: "#{deploy}#"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector: 
    app: web
    version: "#{deploy}#"
  type: LoadBalancer