apiVersion: v1
kind: Service
metadata: 
  name: web-service-temp
  labels: 
    name: web
    type: "#{deploy}#"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector: 
    app: web
    type: "#{deploy}#"
  type: NodePort